---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu and update repository index
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages for RedHat and update repository index
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat"
